/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_CRYPTOCLIENT_H_
#define JSONRPC_CPP_STUB_CRYPTOCLIENT_H_

#include <jsonrpccpp/client.h>

class CryptoClient : public jsonrpc::Client
{
    public:
        CryptoClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value getinfo() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            Json::Value result = this->CallMethod("getinfo",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value account(const std::string& account) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["account"] = account;
            Json::Value result = this->CallMethod("account",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        bool sendtoaddress(const std::string& address, double amount, double fee) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["address"] = address;
            p["amount"] = amount;
            p["fee"] = fee;
            Json::Value result = this->CallMethod("sendtoaddress",p);
            if (result.isBool())
                return result.asBool();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_CRYPTOCLIENT_H_
